#!/bin/bash


yes="y"
no="n"


mkdir "karpbox"
cd "karpbox" && touch "arnolddennis.net"


echo "I am about to create a directory structure named 'Karpbox'."
echo "Do you want me to proceed? (y/n)"


read "userInput"

if [[ "$userInput" != "$no" ]]; then


mkdir "bin"
mkdir "internals"
mkdir "migrations"
mkdir "remote"
mkdir "go.mod"
mkdir "Makefile"
mkdir "cmd"
cd "cmd"
mkdir "api"
cd "api"
touch "main.go"

echo "package main" >> "main.go"
echo 'import "fmt" ' >> "main.go"
echo "func main () {" >> "main.go"
echo 'fmt.Println ("Hello World")' >> "main.go"
echo "}" >> "main.go"


echo "I have created a *main.go* file for you to test the directory structure."
echo "Type *go run ./cmd/api* at the root directory of your project to test your project. "
else

echo "aborted program"

exit
fi

